---
deployment:
  tasks:
    - export DEPLOYPATH=/home/dixonweb/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp asset-manifest.json $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp manifest.json $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R static $DEPLOYPATH
